accounts/urls.py
from django.urls import path
from .views import sign_up, sign_in, logout_user

app_name = 'accounts'

urlpatterns = [
    path('sign_up/', sign_up, name='sign_up'),
    path('sign_in/', sign_in, name='sign_in'),
    path('logut/', logout_user, name='logout_user'),
]

educational_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('university.urls')),
    path('', include('accounts.urls')),
    path('', include('library.urls')),
]

library/urls.py
from django.urls import path
from .views import BooksListView, rent_book

app_name = 'library'

urlpatterns = [
    path('', BooksListView.as_view(), name='books_list'),
    path('rent/<int:book_id>/', rent_book, name='rent_book'),
]

university/urls.py
from django.urls import path
from .views import ClassesListView, get_lessons_and_students, register_student

app_name = 'university'

urlpatterns = [
    path('', ClassesListView.as_view(), name='index'),
    path('student_list/<int:class_id>/', get_lessons_and_students, name='students_list'),
    path('register_students/', register_student, name='registere_students'),
]

library/models.py
from django.db import models
from university.models import College, Student, Major


class Book(models.Model):
    name = models.CharField(max_length=150)
    major = models.ForeignKey(Major, on_delete=models.CASCADE)
    is_in_rent = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Book'
        verbose_name_plural = 'Books'
        db_table = 'Books'

class Rent(models.Model):
    book_name = models.ForeignKey(Book, on_delete=models.CASCADE)
    student_name = models.ForeignKey(Student, on_delete=models.CASCADE)
    # Automatically set the field to now when the object is first created.
    rent_start_date = models.DateTimeField(auto_now_add=True)
    rent_end_date = models.DateTimeField()

    def __str__(self):
        return f'{self.book_name}'

    class Meta:
        verbose_name = 'Rent'
        verbose_name_plural = 'Rents'
        db_table = 'Rents'

library/views.py
from django.shortcuts import render
from django.views.generic import ListView
from library.models import Book


class BooksListView(ListView):
    context_object_name = 'Classes'
    queryset = Book.objects.filter(is_in_rent=True)
    template_name = 'library/books_list.html'


def rent_book(request, pk):
    pass

library/templates/library/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          rel="stylesheet">

    {% block css %} {% endblock %}
    <title>{%block title%} {% endblock %}</title>

    <style>
        nav a {
            color: #9f8610;
            text-decoration: none;
        }

        h1 {
            display: flex;
            justify-content: center;
        }

        .alert {
            display: flex;
            justify-content: center;
        }
    </style>

</head>
<body>
{% if user.is_authenticated %}


<nav class="navbar navbar-dark bg-dark" style="color:#9f8610">
    <a class="navbar-link" href="{% url 'university:index' %}">Classes</a>
    <a class="navbar-link" href="{% url 'university:registere_students' %}">Select lessons</a>
    <a class="navbar-link" href="{% url 'library:rent_book' %}">Rent a book</a>
    <a class="navbar-link" href="{% url 'accounts:logout_user' %}">Logout</a>

</nav>
<h1> Hello {{user}} </h1>


{% if messages %}
<div class="alert alert-success" role="alert">
    {% for message in messages %}
    <h6> {{message}} </h6>
    {% endfor %}
</div>

{% endif %}

{% else %}

<nav class="navbar navbar-dark bg-dark" style="color:#9f8610">
    <a class="navbar-link" href="{% url 'university:index' %}">Classes</a>
    <a class="navbar-link" href="{% url 'accounts:sign_up' %}">Sign up</a>
    <a class="navbar-link" href="{% url 'accounts:sign_in' %}">Sign in </a>
</nav>

{% endif %}
{% block content %} {% endblock %}
</body>
</html>

library/templates/library/books_list.html
{% extends 'library/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'university/index.css' %}" rel="stylesheet">
{% endblock %}
<style>
    body {
        background-color: white;
    }
</style>
{% block content %}

<div class="container-fluid centering">



    <div class="row centering">


        <div class="col-12 centering">

            <table class="table table-hover">

                <thead>
                <tr>
                    <th scope="col">Book name</th>
<!--                    <th scope="col">College name</th>-->
<!--                    <th scope="col">Class day</th>-->
<!--                    <th scope="col">professor name</th>-->
                </tr>
                </thead>

                <tbody>

                {% for each in Classes %}

                <tr>
                    <td><a class="classLinks" href="{% url 'university:students_list' each.id %}"> {{ each }} </a></td>
                    <td>{{ each.college_name }}</td>
                    <td>{{each.class_day}}</td>
                    <td>{{each.professor_name}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

</div>
{% endblock %}

library/templates/library/rent_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>